CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

-- CREATE DATABASE safra;

-- CREATE TABLE IF NOT EXISTS products (
--   id VARCHAR(36) NOT NULL PRIMARY KEY,
--   name VARCHAR(255) NOT NULL,
--   price VARCHAR(255) NOT NULL UNIQUE,
--   category VARCHAR(255) NOT NULL,
--   validity VARCHAR(50) NOT NULL,
-- );