CREATE TABLE IF NOT EXISTS categorys (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  description VARCHAR(200) NOT NULL,
  type VARCHAR(100) NOT NULL,
  validity VARCHAR(50) NOT NULL,
  photo VARCHAR(255) NOT NULL,
  idCategory INT NOT NULL,
  FOREIGN KEY (idCategory) REFERENCES categorys(id)
);